# update all the pre-commit hooks - `pre-commit autoupdate`
default_language_version:
  pytho`: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0 # Consider updating rev
    hooks:
      # Keep your existing hooks here
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: check-executables-have-shebangs
      - id: check-toml
      - id: check-case-conflict
      - id: check-added-large-files

  # NEW: Add Ruff hook
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Find the latest version on GitHub Releases
    rev: v0.11.6 # Use the latest stable version
    hooks:
      # Run the linter (checks + fixes)
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix] # Apply fixes and fail if fixes were made
      # Run the formatter
      - id: ruff-format

  # REMOVED: black hook (replaced by ruff-format)
  # REMOVED: isort hook (replaced by ruff --fix with 'I' rule enabled)
  # REMOVED: pyupgrade hook (replaced by ruff --fix with 'UP' rule enabled)
  # REMOVED: flake8 hook (replaced by ruff)

  # Keep python security linter
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.3 # Consider updating rev
    hooks:
      - id: bandit
        args: ["-s", "B101"] # Keep your bandit args

  # Keep yaml formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8 # Consider updating rev
    hooks:
      - id: prettier
        types: [yaml]

  # Keep shell scripts linter
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1 # Consider updating rev
    hooks:
      - id: shellcheck

  # Keep md formatting
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.22 # Consider updating rev
    hooks:
      - id: mdformat
        args: ["--number"]
        additional_dependencies:
          - mdformat-gfm
          - mdformat-tables
          - mdformat_frontmatter
          # - mdformat-toc
          # - mdformat-black

  # Keep word spelling linter
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1 # Consider updating rev
    hooks:
      - id: codespell
        args: 
          - --skip=logs/**,data/**,*.ipynb
          - --ignore-words-list=abc,def,fpr,tpr,roc_auc,auc

  # Keep jupyter notebook linting (but update to use ruff)
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.1 
    hooks:
      # Replace nbqa-black, nbqa-isort, nbqa-flake8 with nbqa-ruff
      - id: nbqa-ruff
        args: [--fix, --exit-non-zero-on-fix] # Apply fixes within notebooks
      # You might also want to run the formatter on notebooks
      - id: nbqa-ruff-format

  # Keep commented out hooks if desired
  # # python docstring formatting
  # - repo: https://github.com/myint/docformatter
  # # jupyter notebook cell output clearing
  # - repo: https://github.com/kynan/nbstripout
