# In your common config file (e.g., configs/common/default.yaml or similar)
color_palette:
  _target_: supervision.ColorPalette.from_hex
  color_hex_list:
    - "#FFFF00" # Yellow
    - "#FF0000" # Red
    - "#00FF00" # Green
    - "#FFFFFF" # White
