# path to root directory
# this requires PROJECT_ROOT environment variable to exist
# PROJECT_ROOT is inferred and set by pyrootutils package in `train.py` and `eval.py`
root_dir: ${oc.env:PROJECT_ROOT}

# path to data directory
root_data_dir: ${oc.env:DATA_ROOT}

# path to results directory
results_dir: ${paths.root_dir}/results

# path to logging directory
log_dir: ${paths.root_dir}/logs/

# path to output directory, created dynamically by hydra
# path generation pattern is specified in `configs/hydra/default.yaml`
# use it to store all files generated during the run, like ckpts and metrics
output_dir: ${hydra:runtime.output_dir}

# path to working directory
work_dir: ${hydra:runtime.cwd}

pretrained_model_dir: ${paths.root_dir}/pretrained_models
embedded_model_name: google/siglip-base-patch16-224

train_bst_model: ${paths.root_dir}/results/augumented-data-yolo12l/weights/final_best.pt
train_lst_model: ${paths.root_dir}/results/faugumented-data-yolo12l/weights/final_last.pt

ip_vid_path: ${paths.root_dir}/${datasets.datasets_dir}/0bfacc_0.mp4
processed_vid_path: ${paths.results_dir}/${models.model_name}_processed_0bfacc_0.mp4
