# Ultralytics 🚀 AGPL-3.0 License - https://ultralytics.com/license

# Default Ultralytics settings for ByteTrack tracker when using mode="track"
# For documentation and examples see https://docs.ultralytics.com/modes/track/
# For ByteTrack source code see https://github.com/ifzhang/ByteTrack

_target_: supervision.ByteTrack
track_activation_threshold: 0.20
lost_track_buffer: 90
minimum_matching_threshold: 0.75
frame_rate: 30
minimum_consecutive_frames: 1
