# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - datasets: default
  - paths: default
  - extras: default
  - hydra: default
  - models: default
  - trainer: default
  - tracker: default
  - annotate: default
  - common: color_palette

  # model config (enable through command line, e.g. `python train.py model=default`)-

  # debugging config (enable through command line, e.g. `python train.py debug=default)
  - debug: null

# task name, determines output directory path
task_name: "augumented-data-inference-${models.model_name}"

# tags to help you identify your experiments
# you can overwrite this in experiment configs
# overwrite from command line with `python train.py tags="[first_tag, second_tag]"`
# appending lists from command line is currently not supported :(
# https://github.com/facebookresearch/hydra/issues/1547
tags: ["deploy"]

# seed for random number generators in pytorch, numpy and python.random
seed: 42

# https://docs.ultralytics.com/modes/predict/#inference-arguments
args:
  # must give project path or else - Error: No such file or directory: 'runs/detect/train/weights/best.pt' or permission denied
  project: ${paths.results_dir}
  name: inference-${task_name}
  imgsz: [1280, 1280]
  conf: 0.3
  iou: 0.7
  half: True # Enables half-precision (FP16) computation,
  device: 0 # cuda device, i.e. 0 or 0,1,2,3 or cpu
  plots: True
  verbose: True # print all verbose
  workers: 16
  batch: 1
  agnostic_nms: True # Enables class-agnostic Non-Maximum Suppression (NMS), which merges overlapping boxes of different classes. Useful in multi-class detection scenarios where class overlap is common.
  stream: False # Enables memory-efficient processing for long videos or numerous images by returning a generator of Results objects instead of loading all frames into memory at once.
