# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - datasets: default
  - paths: default
  - extras: default
  - hydra: default
  - model: default 


  # debugging config (enable through command line, e.g. `python train.py debug=default)
  - debug: null

# task name, determines output directory path
task_name: "augumented-data-${model.model_name}"

# tags to help you identify your experiments
# you can overwrite this in experiment configs
# overwrite from command line with `python train.py tags="[first_tag, second_tag]"`
# appending lists from command line is currently not supported :(
# https://github.com/facebookresearch/hydra/issues/1547
tags: ["deploy"]

# set False to skip model training
train: True

# evaluate on test set, using best model weights achieved during training
# lightning chooses best weights based on the metric specified in checkpoint callback
test: False

# simply provide checkpoint path to resume training
ckpt_path: null

# seed for random number generators in pytorch, numpy and python.random
seed: 42


args:
# must give project path or else - Error: No such file or directory: 'runs/detect/train/weights/best.pt' or permission denied
  project: ${paths.results_dir}
  name: inference-${task_name}
  imgsz: 1280
  half: True  # Enables half-precision (FP16) computation,
  device: 0 # cuda device, i.e. 0 or 0,1,2,3 or cpu
  plots: True
  verbose: True # print allverbose
  workers: 16
